services:

  mariadb:
    container_name: Database
    image: mariadb:10.11.6-jammy
    environment:
      - MYSQL_DATABASE=phone-book
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/db/:/var/lib/mysql:delegated

  php:
    container_name: PHP
    build:
      context: ./..
      dockerfile: ./.docker/php/Dockerfile
    working_dir: /srv
    volumes:
      - ./../:/srv:delegated

  nginx:
    container_name: Nginx
    image: nginx:1.20.2-alpine
    volumes:
      - ./../www:/srv/www:delegated
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template:delegated
    environment:
      - NGINX_PHP_HOST=php
    ports:
      - "80:80"

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin:5.2.1-apache
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "10000:80"